sudo: false
language: node_js
cache:
  directories:
  - node_modules

node_js:
  - '4'
  - '5'
  - '6'
  - '7'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install
  - yarn run bootstrap

script:
  - node --version
  - npm --version
  - yarn --version
  - ./node_modules/.bin/eslint --version
  - yarn run lint
  - yarn run test -- --runInBand

after_success:
  - bash <(curl -s https://codecov.io/bash)